// All-in-one header
// SPEL definitions
#include "predef.hpp"

#include "bodyJoint.hpp"
#include "bodyPart.hpp"
#include "colorHistDetector.hpp"
#include "detector.hpp"
#include "frame.hpp"
#include "hogDetector.hpp"
#include "imagesimilaritymatrix.hpp"
#include "interpolation.hpp"
#include "keyframe.hpp"
#include "limbLabel.hpp"
#include "lockframe.hpp"
#include "minspanningtree.hpp"
#include "nskpsolver.hpp"
#include "score.hpp"
#include "sequence.hpp"
#include "skeleton.hpp"
#include "solution.hpp"
#include "solver.hpp"
#include "solvlet.hpp"
#include "spelHelper.hpp"
#include "surfDetector.hpp"
#include "tlpssolver.hpp"
